// This file is auto-generated by Supabase CLI:
//   npm run db:types
//
// The stub below lets the app compile before you've generated real types.
// Replace it entirely once you run the command.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          avatar_url: string | null;
          bio: string | null;
          is_author: boolean;
          onboarded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name: string;
          avatar_url?: string | null;
          bio?: string | null;
          is_author?: boolean;
          onboarded_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      authors: {
        Row: {
          id: string;
          pen_name: string | null;
          tagline: string | null;
          total_sparks_received: number;
          total_reads: number;
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          pen_name?: string | null;
          tagline?: string | null;
        };
        Update: Partial<Database['public']['Tables']['authors']['Insert']>;
      };
      donation_links: {
        Row: {
          id: string;
          author_id: string;
          platform: string;
          label: string | null;
          url: string;
          is_primary: boolean;
          is_active: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          author_id: string;
          platform: string;
          label?: string | null;
          url: string;
          is_primary?: boolean;
          is_active?: boolean;
          display_order?: number;
        };
        Update: Partial<Database['public']['Tables']['donation_links']['Insert']>;
      };
      // Add remaining tables after you generate real types.
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
